<?php

namespace OpcacheBundle\Repository;

/**
 * OpcacheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OpcacheRepository extends \Doctrine\ORM\EntityRepository
{
}
